### PR TITLE
Create webpack.yml

### PR DESCRIPTION
**Pull request by dav3yblaz3**

### CODE REVIEW

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Review by dav3yblaz3 — COMMENTED** [review]
Looks good? Is i working?

**Review by dav3yblaz3 — COMMENTED** [review]
sorry so late for review. looks good! thank you!

**Review by dav3yblaz3 — COMMENTED** [review]
good job!

**Review by dav3yblaz3 — COMMENTED** [review]
Good job!

**Review by dav3yblaz3 — COMMENTED** [review]
Looks fantastic, we should put this in testing immediately! Thank you! Great work!!

**Comment by dav3yblaz3** [comment]
Hello? Are you there? Can we please get this approved? I would like varcil to deploy immediately!

**Review by dav3yblaz3 — COMMENTED** [review]
Nice!

**Review by dav3yblaz3 — COMMENTED** [review]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Review by dav3yblaz3 — COMMENTED** [review]
🙌🕳️🙌🙏♾️😈👾🎩😄👍👍👍👍👍👍👍👍👍👍👍👍👍👍😈😈👍

**Review by dav3yblaz3 — COMMENTED** [review]
Looks like we are progressing as exponentially as relatively possible[]()

**Comment by dav3yblaz3** [comment]
Need help getting this approved please

**Review by dav3yblaz3 — COMMENTED** [review]
Let's get this going

**Review by dav3yblaz3 — COMMENTED** [review]
really coming together thanks can we bump up the profits now i would like to see it do a full power cycle

**Review by dav3yblaz3 — COMMENTED** [review]
seems to be good to test

**Review by dav3yblaz3 — COMMENTED** [review]
one step forward one milestone at a time thank you team

**Review by dav3yblaz3 — COMMENTED** [review]
good job team

**Review by dav3yblaz3 — COMMENTED** [review]
can we get this merged

**Review by dav3yblaz3 — COMMENTED** [review]
not sure what is missing can we get this going now

**Review by dav3yblaz3 — COMMENTED** [review]
can we please get this fixed

**Comment by dav3yblaz3** [comment]
can we get a merger

**Comment by dav3yblaz3** [comment]
lets get this going team

**Comment by dav3yblaz3** [comment]
lets get this taken care of this time thanks greatest team ever

**Pull request closed without merging**
